#pragma once

#define BAUD_RATE 115200

#define BUZZER_PIN 25
#define BUZZER_LEDC_CHANNEL 0

#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 64
#define DISPLAY_DC 2
#define DISPLAY_CS 5
#define DISPLAY_RESET 4

#define MESSAGES_FILE_PATH "/messages.txt"
#define MESSAGE_COUNT 32

#define MESSAGE_CHANGE_BUTTON_PIN 14
#define MESSAGE_CHANGE_BUTTON_DEBOUNCE_TIME 1000 * 60 // 30 minutes

#define DISPLAY_BUTTON_VIEW_SWITCH_PIN 32

#define BUTTON_PRESS_DEBOUNCE_TIME 50

#define ALARM_TIME_HOUR 8

#define TOTAL_IMAGES_IN_BIN 10
#define IMAGE_SIZE_BYTES 1024